[2022-06-18 07:29:45,042] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_demo-v2.delete_residuals manual__2022-06-18T07:29:03.561175+00:00 [queued]>
[2022-06-18 07:29:45,052] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_demo-v2.delete_residuals manual__2022-06-18T07:29:03.561175+00:00 [queued]>
[2022-06-18 07:29:45,052] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 07:29:45,052] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-18 07:29:45,052] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 07:29:45,065] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): delete_residuals> on 2022-06-18 07:29:03.561175+00:00
[2022-06-18 07:29:45,070] {standard_task_runner.py:52} INFO - Started process 2722 to run task
[2022-06-18 07:29:45,072] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coffee_lake_demo-v2', 'delete_residuals', 'manual__2022-06-18T07:29:03.561175+00:00', '--job-id', '619', '--raw', '--subdir', 'DAGS_FOLDER/scraper_v2_dag.py', '--cfg-path', '/tmp/tmpctcif7ew', '--error-file', '/tmp/tmpw20b514l']
[2022-06-18 07:29:45,073] {standard_task_runner.py:80} INFO - Job 619: Subtask delete_residuals
[2022-06-18 07:29:45,118] {task_command.py:370} INFO - Running <TaskInstance: coffee_lake_demo-v2.delete_residuals manual__2022-06-18T07:29:03.561175+00:00 [running]> on host 312614bad459
[2022-06-18 07:29:45,180] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=coffee_lake_demo-v2
AIRFLOW_CTX_TASK_ID=delete_residuals
AIRFLOW_CTX_EXECUTION_DATE=2022-06-18T07:29:03.561175+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-18T07:29:03.561175+00:00
[2022-06-18 07:29:45,185] {logging_mixin.py:115} INFO - business_world_2022-06-18_07-29-13.csv
[2022-06-18 07:29:45,187] {logging_mixin.py:115} INFO - images
[2022-06-18 07:29:45,188] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraper_v2_dag.py", line 253, in delete_residuals
    os.rmdir(outfile)
OSError: [Errno 39] Directory not empty: '/opt/airflow/data/images'
[2022-06-18 07:29:45,200] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coffee_lake_demo-v2, task_id=delete_residuals, execution_date=20220618T072903, start_date=20220618T072945, end_date=20220618T072945
[2022-06-18 07:29:45,219] {standard_task_runner.py:97} ERROR - Failed to execute job 619 for task delete_residuals ([Errno 39] Directory not empty: '/opt/airflow/data/images'; 2722)
[2022-06-18 07:29:45,246] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-18 07:29:45,424] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
