[2022-06-17 16:28:13,636] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.spacey manual__2022-06-17T16:28:00.040992+00:00 [queued]>
[2022-06-17 16:28:13,652] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.spacey manual__2022-06-17T16:28:00.040992+00:00 [queued]>
[2022-06-17 16:28:13,653] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 16:28:13,653] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-17 16:28:13,653] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 16:28:13,664] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): spacey> on 2022-06-17 16:28:00.040992+00:00
[2022-06-17 16:28:13,668] {standard_task_runner.py:52} INFO - Started process 1249 to run task
[2022-06-17 16:28:13,671] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coffee_lake_scrapers-v1', 'spacey', 'manual__2022-06-17T16:28:00.040992+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/scraper_dag.py', '--cfg-path', '/tmp/tmp4jhx0z0r', '--error-file', '/tmp/tmpc1kp6xvi']
[2022-06-17 16:28:13,672] {standard_task_runner.py:80} INFO - Job 161: Subtask spacey
[2022-06-17 16:28:13,720] {task_command.py:370} INFO - Running <TaskInstance: coffee_lake_scrapers-v1.spacey manual__2022-06-17T16:28:00.040992+00:00 [running]> on host 2f484ba01a8b
[2022-06-17 16:28:13,776] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=coffee_lake_scrapers-v1
AIRFLOW_CTX_TASK_ID=spacey
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T16:28:00.040992+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T16:28:00.040992+00:00
[2022-06-17 16:28:13,800] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraper_dag.py", line 100, in test_spacey
    nlp = spacy.load(r"/opt/airflow/model/en_core_web_sm")
  File "/home/airflow/.local/lib/python3.7/site-packages/spacy/__init__.py", line 52, in load
    name, vocab=vocab, disable=disable, exclude=exclude, config=config
  File "/home/airflow/.local/lib/python3.7/site-packages/spacy/util.py", line 422, in load_model
    return load_model_from_path(Path(name), **kwargs)  # type: ignore[arg-type]
  File "/home/airflow/.local/lib/python3.7/site-packages/spacy/util.py", line 487, in load_model_from_path
    config = load_config(config_path, overrides=overrides)
  File "/home/airflow/.local/lib/python3.7/site-packages/spacy/util.py", line 650, in load_config
    raise IOError(Errors.E053.format(path=config_path, name="config file"))
OSError: [E053] Could not read config file from /opt/***/model/en_core_web_sm/config.cfg
[2022-06-17 16:28:13,813] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coffee_lake_scrapers-v1, task_id=spacey, execution_date=20220617T162800, start_date=20220617T162813, end_date=20220617T162813
[2022-06-17 16:28:13,827] {standard_task_runner.py:97} ERROR - Failed to execute job 161 for task spacey ([E053] Could not read config file from /opt/***/model/en_core_web_sm/config.cfg; 1249)
[2022-06-17 16:28:13,884] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-17 16:28:13,935] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
