[2022-06-17 18:52:44,302] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.upload_imgs manual__2022-06-17T18:52:11.192765+00:00 [queued]>
[2022-06-17 18:52:44,316] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.upload_imgs manual__2022-06-17T18:52:11.192765+00:00 [queued]>
[2022-06-17 18:52:44,317] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 18:52:44,317] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-17 18:52:44,317] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 18:52:44,332] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): upload_imgs> on 2022-06-17 18:52:11.192765+00:00
[2022-06-17 18:52:44,337] {standard_task_runner.py:52} INFO - Started process 735 to run task
[2022-06-17 18:52:44,339] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coffee_lake_scrapers-v1', 'upload_imgs', 'manual__2022-06-17T18:52:11.192765+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/scraper_dag.py', '--cfg-path', '/tmp/tmpmug6bfni', '--error-file', '/tmp/tmp4_rg7q2p']
[2022-06-17 18:52:44,340] {standard_task_runner.py:80} INFO - Job 252: Subtask upload_imgs
[2022-06-17 18:52:44,383] {task_command.py:370} INFO - Running <TaskInstance: coffee_lake_scrapers-v1.upload_imgs manual__2022-06-17T18:52:11.192765+00:00 [running]> on host c0a717b7b476
[2022-06-17 18:52:44,446] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=coffee_lake_scrapers-v1
AIRFLOW_CTX_TASK_ID=upload_imgs
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T18:52:11.192765+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T18:52:11.192765+00:00
[2022-06-17 18:52:44,460] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraper_dag.py", line 161, in upload_imgs
    upload_img_to_gcs(img=img, uploaded_filename=outfile)
  File "/opt/airflow/dags/scraper_dag.py", line 190, in upload_img_to_gcs
    decoded_img = pybase64.b64decode(img)
TypeError: a bytes-like object is required, not 'PngImageFile'
[2022-06-17 18:52:44,471] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coffee_lake_scrapers-v1, task_id=upload_imgs, execution_date=20220617T185211, start_date=20220617T185244, end_date=20220617T185244
[2022-06-17 18:52:44,481] {standard_task_runner.py:97} ERROR - Failed to execute job 252 for task upload_imgs (a bytes-like object is required, not 'PngImageFile'; 735)
[2022-06-17 18:52:44,512] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-17 18:52:44,551] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
